DROP TABLE IF EXISTS albums;
DROP TABLE IF EXISTS artists;

CREATE TABLE artists (
  id SERIAL8 PRIMARY KEY,
  genre VARCHAR(255),
  artist VARCHAR(255),
);

CREATE TABLE albums ({
  id SERIAL8 PRIMARY KEY,
  name VARCHAR(255)
  });
